language: python
sudo: required
python:
  - "2.7"
  - "3.4"
  - "3.5"

install: 
  - pip install -U pip
  - pip install numpy==1.12.0 scipy==0.18.1
  - pip install scikit-learn==0.18.1
  - pip install pytest==3.0.5
  - pip install pandas==0.18.1

script: pytest test_rent.py

