language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
before_install:
- pip install -U pip

install: 
- pip install -r requirements.txt
# command to run tests
script: pytest