language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
- "pip install -U pip"
#- "pip install -U pandas scikit-learn numpy matplotlib nbconvert ipykernel"
- "pip install -U pandas scikit-learn numpy matplotlib nbconvert jupyter_client ipykernel scipy"
# command to run tests
script: travis_wait jupyter-nbconvert --execute hw4_starter_notebook.ipynb
